[[pages]]
path = "Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/01_Deploy_Scripts.py"
name = "Deploy Scripts"
icon = "ğŸ“œ"

[[pages]]
path = "pages/02_Settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "pages/03_Email_Display.py"
name = "Email Display"
icon = "ğŸ“¥"

[[pages]]
path = "pages/04_Attachments.py"
name = "Attachments"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "pages/05_Database_Display.py"
name = "Database Display"
icon = "ğŸ“Š"

